from avina_speech.tts import speak

def tutorial():
    speak("Let's go over the buttons real quick.")
    speak("First, make sure to have my program focused.")
    speak("I'll take care of translating your button presses into the game")
    speak("so that when you press Up you will always go North, just as one example.")
    speak("C is your button for confirm, so any time you want to select a menu item or")
    speak("similar actions. X is your 'go back' button.")
    speak("V is your button to open the menu.")
    speak("Z is used in some rare cases as well.")
    speak("B is your Start button, but rarely used.")
    speak("S and D are like bumper buttons on a controller, rarely used.")
    speak("Those are the main buttons just like in the game, but I've got some")
    speak("extra functionality too. For example.")
    speak("If you are near to an actor, you can press A and I will approach and speak with them.")
    speak("I'll let you know when you're near someone or something.")
    speak("This will also work on objects like chests or save spheres.")
    speak("If you want to know where you are on the map, you can press O for Coordinates.")
    speak("In addition, I've got a recall system.")
    speak("While in control, press R for recall to set a recall point.")
    speak("To go back, press E for recall to go back to your recall point.")
    speak("Oh, sorry, it seems like my functionality is still a bit limited.")
    speak("After all, I'm only a virtual intelligence, not truly artificial.")
    speak("I can only do the things my programmer has set me up to do.")
    speak("Don't worry, my programmer is still working on improving me.")
    